version: "2"
networks:
  default:
    driver: bridge

services:
  node-app-demo:
    restart: always
    # 镜像
    image: luqiangzeng/node-v16.14.0:1.0.0
    container_name: node-app-demo
    ports:
      - "9090:9090"
    command: /usr/sbin/init
