version: "2"
networks:
  default:
    driver: bridge

services:
  nginx-demo:
    restart: always
    # 镜像
    image: luqiangzeng/nginx-demo:1.0.0
    container_name: nginx-demo
    # 将容器中Nginx根目录(`/opt/app/nginx`) 挂载至本机的目录上
    volumes:
      - /home/coder/app/nginx-demo/html:/opt/app/nginx
    ports:
      - "80:80"
      # 若开启 https 可以映射443端口
      # - "443:443"
    command: /usr/sbin/init
