version: "2"
networks:
  default:
    driver: bridge

services:
  hexo-blog:
    restart: always
    # 镜像
    image: luqiangzeng/hexo-blog:1.0.0
    container_name: hexo-blog
    ports:
      - "80:80"
      # 若开启 https 可以映射443端口
      # - "443:443"
    command: /usr/sbin/init
