# 静态文件挂载
# mkdir -p /data/coder/app/ueditor/static-page

version: "2"
networks:
  default:
    driver: bridge

services:
  ueditor-1.5.0:
    restart: always
    # 镜像
    image: luqiangzeng/ueditor-1.5.0:1.0.0
    container_name: ueditor-1.5.0
    # volumes:
    #   # 挂载 static-page
    #   - /data/coder/app/ueditor/static-page:/opt/app/nginx/static-page
    ports:
      - "80:80"
      # 若开启 https 可以映射443端口
      # - "443:443"
    command: /usr/sbin/init
